services:
    ## Real services
    editor_frontend:
        class: con4gis\EditorBundle\Classes\EditorMapFrontend
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@event_dispatcher'

