services:
    ## Real services
    editor_frontend:
        class: con4gis\EditorBundle\Classes\EditorMapFrontend
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@event_dispatcher'

    editor_history:
        class: con4gis\EditorBundle\Classes\Services\EditorHistoryService
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@logger'

    editor_plugin_service:
        class: con4gis\EditorBundle\Classes\Services\PluginService
        public: true
        arguments:
            - '@event_dispatcher'
            - '@service_container'
            - '@file_locator'
