services:
    ## Real services
    editor_frontend:
        class: con4gis\EditorBundle\Classes\EditorMapFrontend
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@event_dispatcher'

    editor_history:
        class: con4gis\EditorBundle\Classes\Services\EditorHistoryService
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@logger'

    editor_plugin_service:
        class: con4gis\EditorBundle\Classes\Services\PluginService
        public: true
        arguments:
            - '@event_dispatcher'
            - '@service_container'
            - '@file_locator'

    con4gis\EditorBundle\Controller\CategoryController:
        class: con4gis\EditorBundle\Controller\CategoryController
        public: true
        arguments:
            - "@service_container"

    con4gis\EditorBundle\Controller\DataPopupController:
        class: con4gis\EditorBundle\Controller\DataPopupController
        public: true
        arguments:
            - "@service_container"

    con4gis\EditorBundle\Controller\EditorController:
        class: con4gis\EditorBundle\Controller\EditorController
        public: true
        arguments:
            - "@service_container"

    con4gis\EditorBundle\Controller\ElementController:
        class: con4gis\EditorBundle\Controller\ElementController
        public: true
        arguments:
            - "@service_container"

    con4gis\EditorBundle\Controller\ElementTypeController:
        class: con4gis\EditorBundle\Controller\ElementTypeController
        public: true
        arguments:
            - "@service_container"

    con4gis\EditorBundle\Controller\ProjectController:
        class: con4gis\EditorBundle\Controller\ProjectController
        public: true
        arguments:
            - "@service_container"