services:
    ## Create data
    editor.onDataCreateCreateEntity:
        class: con4gis\EditorBundle\Classes\Listener\CreateDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.create, method: onDataCreateCreateEntity, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@editor_frontend'

    editor.onDataCreateCreateReturnData:
        class: con4gis\EditorBundle\Classes\Listener\CreateDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.create, method: onDataCreateCreateReturnData, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@editor_frontend'

    ## Delete data
    editor.onDataDeleteGetEntities:
        class: con4gis\EditorBundle\Classes\Listener\DeleteDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.delete, method: onDataDeleteGetEntities, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onDataDeleteDeleteEntity:
        class: con4gis\EditorBundle\Classes\Listener\DeleteDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.delete, method: onDataDeleteDeleteEntities, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Change data
    editor.onDataChangeUpdateEntity:
        class: con4gis\EditorBundle\Classes\Listener\ChangeDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.change, method: onDataChangeUpdateEntity, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@editor_history'

    ## Load Metadata Dialog
    editor.onShowMetadataDialogGetFieldList:
        class: con4gis\EditorBundle\Classes\Listener\ShowMetadataDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.show, method: onShowMetadataDialogGetFieldList, priority: 4096 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onShowMetadataDialogGetDialogParams:
        class: con4gis\EditorBundle\Classes\Listener\ShowMetadataDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.show, method: onShowMetadataDialogGetDialogParams, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onShowMetadataGetData:
        class: con4gis\EditorBundle\Classes\Listener\ShowMetadataDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.show, method: onShowMetadataGetData, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onShowMetadataDialogGenerateHtml:
        class: con4gis\EditorBundle\Classes\Listener\ShowMetadataDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.show, method: onShowMetadataDialogGenerateHtml, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Save metadata
    editor.onSaveMetadataGetEntities:
        class: con4gis\EditorBundle\Classes\Listener\SaveMetadataListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.save, method: onSaveMetadataGetEntities, priority: 4096 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveMetadataFillEntities:
        class: con4gis\EditorBundle\Classes\Listener\SaveMetadataListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.save, method: onSaveMetadataFillEntities, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveMetadataExecBeforeSave:
        class: con4gis\EditorBundle\Classes\Listener\SaveMetadataListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.save, method: onSaveMetadataExecBeforeSave, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveMetadataValidateFieldValues:
        class: con4gis\EditorBundle\Classes\Listener\SaveMetadataListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.save, method: onSaveMetadataValidateFieldValues, priority: 1900 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveMetadataCheckMandatory:
        class: con4gis\EditorBundle\Classes\Listener\SaveMetadataListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.save, method: onSaveMetadataCheckMandatory, priority: 1800 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveMetadataPersistEntities:
        class: con4gis\EditorBundle\Classes\Listener\SaveMetadataListener
        tags:
            - { name: kernel.event_listener, event: editor.metadata.save, method: onSaveMetadataPersistEntities, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Get popup
    editor.onGetPopupGetFields:
        class: con4gis\EditorBundle\Classes\Listener\GetPopupListener
        tags:
            - { name: kernel.event_listener, event: editor.popup.get, method: onGetPopupGetFields, priority: 4096 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onGetPopupGetData:
        class: con4gis\EditorBundle\Classes\Listener\GetPopupListener
        tags:
            - { name: kernel.event_listener, event: editor.popup.get, method: onGetPopupGetData, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onGetPopupCreateView:
        class: con4gis\EditorBundle\Classes\Listener\GetPopupListener
        tags:
            - { name: kernel.event_listener, event: editor.popup.get, method: onGetPopupCreateView, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## duplicate data
    editor.onDuplicateDataGetEntities:
        class: con4gis\EditorBundle\Classes\Listener\DuplicateDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.duplicate, method: onDuplicateDataGetEntities, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@editor_frontend'

    editor.onDuplicateDataCreateNewEntities:
        class: con4gis\EditorBundle\Classes\Listener\DuplicateDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.duplicate, method: onDuplicateDataCreateNewEntities, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@editor_frontend'

    editor.onDuplicateDataCreateFrontendLayer:
        class: con4gis\EditorBundle\Classes\Listener\DuplicateDataListener
        tags:
            - { name: kernel.event_listener, event: editor.data.duplicate, method: onDuplicateDataCreateFrontendLayer, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@editor_frontend'