services:
    ## Configurate editor
#    editor.onEditorConfigurationLoadScenarios:
#        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
#        tags:
#            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationLoadScenarios, priority: 6144 }
#        arguments:
#            - '@doctrine.orm.default_entity_manager'

    editor.onEditorConfigurationLoadElements:
        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
        tags:
            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationLoadElements, priority: 5120 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditorConfigurationLoadCategories:
        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
        tags:
            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationLoadCategories, priority: 4096 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditorConfigurationSortData:
        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
        tags:
            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationSortData, priority: 4095 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditorConfigurationConvertElements:
        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
        tags:
            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationConvertElements, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditorConfigurationGetDrawStyles:
        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
        tags:
            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationGetDrawStyles, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditorConfigurationGetApiConfig:
        class: con4gis\EditorBundle\Classes\Listener\EditorConfigurationListener
        tags:
            - { name: kernel.event_listener, event: editor.editor.config, method: onEditorConfigurationGetApiConfig, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Load Layers (event from MapsBundle)
    editor.onLoadLayersGetProjectData:
        class: con4gis\EditorBundle\Classes\EditorMapFrontend
        tags:
            - { name: kernel.event_listener, event: maps.layers.load, method: onLoadLayersGetProjectData, priority: 4096 }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - "@event_dispatcher"

    ## Load resources
    editor.onLoadMapResourcesLoadEditorFiles:
        class: con4gis\EditorBundle\Classes\Listener\LoadMapResourcesListener
        tags:
            - { name: kernel.event_listener, event: maps.resources.load, method: onLoadMapResourcesLoadEditorFiles, priority: 1024 }
