services:
    ## Instantiate data plugins
    editor.onInstantiatePluginsGetElement:
        class: con4gis\EditorBundle\Classes\Listener\InstantiateDataPluginsListener
        tags:
            - { name: kernel.event_listener, event: editor.dataplugins.instantiate, method: onInstantiatePluginsGetElement, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onInstantiatePluginsFilterPlugins:
        class: con4gis\EditorBundle\Classes\Listener\InstantiateDataPluginsListener
        tags:
            - { name: kernel.event_listener, event: editor.dataplugins.instantiate, method: onInstantiatePluginsFilterPlugins, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onInstantiatePluginsInstantiatePlugins:
        class: con4gis\EditorBundle\Classes\Listener\InstantiateDataPluginsListener
        tags:
            - { name: kernel.event_listener, event: editor.dataplugins.instantiate, method: onInstantiatePluginsInstantiatePlugins, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Instantiate project plugins
    editor.onInstantiateProjectPluginsInstantiatePlugins:
        class: con4gis\EditorBundle\Classes\Listener\InstantiateProjectPluginsListener
        tags:
            - { name: kernel.event_listener, event: editor.projectplugins.instantiate, method: onInstantiateProjectPluginsInstantiatePlugins, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'