services:
    ## Load projects
    editor.onLoadProjectsGetGenericProjects:
        class: con4gis\EditorBundle\Classes\Listener\LoadProjectsListener
        tags:
            - { name: kernel.event_listener, event: editor.load.projects, method: onLoadProjectsGetGenericProjects, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Create project
    editor.onCreateProjectGetFieldList:
        class: con4gis\EditorBundle\Classes\Listener\CreateProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.create, method: onCreateProjectGetFieldList, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onCreateProjectGetDialogParams:
        class: con4gis\EditorBundle\Classes\Listener\CreateProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.create, method: onCreateProjectGetDialogParams, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onCreateProjectGenerateHtml:
        class: con4gis\EditorBundle\Classes\Listener\CreateProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.create, method: onCreateProjectGenerateHtml, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Save Project
    editor.onSaveProjectGetFieldlist:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectGetFieldlist, priority: 4096 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveProjectExecBeforeSave:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectExecBeforeSave, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveProjectFillData:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectFillData, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'


    editor.onSaveProjectValidateFieldValues:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectValidateFieldValues, priority: 1900 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveProjectCheckMandatory:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectCheckMandatory, priority: 1800 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveProjectSaveEntities:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectSaveEntities, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onSaveProjectLoadPermissions:
        class: con4gis\EditorBundle\Classes\Listener\SaveProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.save, method: onSaveProjectLoadPermissions, priority: 1000 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Delete project
    editor.onDeleteProjectGetEntities:
        class: con4gis\EditorBundle\Classes\Listener\DeleteProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.delete, method: onDeleteProjectGetEntities, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onDeleteProjectDeleteEntities:
        class: con4gis\EditorBundle\Classes\Listener\DeleteProjectListener
        tags:
            - { name: kernel.event_listener, event: editor.project.delete, method: onDeleteProjectDeleteEntities, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    ## Edit Project
    editor.onEditProjectGetFields:
        class: con4gis\EditorBundle\Classes\Listener\ShowEditProjectDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.project.edit, method: onEditProjectGetFields, priority: 3072 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditProjectGetData:
        class: con4gis\EditorBundle\Classes\Listener\ShowEditProjectDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.project.edit, method: onEditProjectGetData, priority: 2048 }
        arguments:
            - '@doctrine.orm.default_entity_manager'

    editor.onEditProjectGetDialog:
        class: con4gis\EditorBundle\Classes\Listener\ShowEditProjectDialogListener
        tags:
            - { name: kernel.event_listener, event: editor.project.edit, method: onEditProjectGetDialog, priority: 1024 }
        arguments:
            - '@doctrine.orm.default_entity_manager'