# Editor config
project_editor_service:
    path: /con4gis/projectEditorService
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectEditor:projectEditor"
    methods: [GET]

# Id service for generated Ids
project_id_service:
    path: /con4gis/projectIdService
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectEditor:getId"
    methods: [POST]

# Save feature
project_data_create:
    path: /con4gis/projectData/{projectId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:createData"
    methods: [POST]

# Delete feature
project_data_delete:
    path: /con4gis/projectData/{projectId}/{dataId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:deleteData"
    methods: [DELETE]

# Update Feature
project_data_update:
    path: /con4gis/projectData/{projectId}/{dataId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:updateData"
    methods: [PUT]

# Duplicate feature
project_data_copy:
    path: /con4gis/projectDataCopy/{projectId}/{dataId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:duplicateData"
    methods: [POST]

# Move feature to another project
project_data_displace:
    path: /con4gis/projectDataDisplace/{dataId}/{newProjectId}/{copy}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:displaceData"
    methods: [POST]

# get Form for metadata
project_data_getForm:
    path: /con4gis/projectDataForm/{projectId}/{dataId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:getForm"
    methods: [GET]

# process form for metadata
project_data_sendForm:
    path: /con4gis/projectDataForm/{projectId}/{dataId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:ProjectData:postForm"
    methods: [POST]

# get form for project
project_create_getList:
    path: /con4gis/project/
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Project:createProject"
    methods: [GET]

# process form for project
project_create_save:
    path: /con4gis/project/
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Project:saveProject"
    methods: [POST]

project_delete:
    path: /con4gis/project
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Project:deleteProject"
    methods: [DELETE]

project_edit:
    path: /con4gis/projectForm/{projectId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Project:editProject"
    methods: [GET]

project_edit_save:
    path: /con4gis/projectForm/{projectId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Project:saveEditedProject"
    methods: [POST]

project_data_popup:
    path: /con4gis/projectData/popup/{dataId}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:DataPopup:getPopup"
    methods: [GET]

get_element_layer:
    path: /con4gis/elements/layer/{layerId}/{pid}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Element:getElementLayer"
    methods: [GET]

get_category_layer:
    path: /con4gis/categories/layer/{layerId}/{pid}/{mid}
    defaults:
        _scope: frontend
        _controller: "con4gisMapsProjectBundle:Category:getCategoryLayer"
    methods: [GET]